// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viettel_post_API.Data;

#nullable disable

namespace Viettel_post_API.Migrations
{
    [DbContext(typeof(Viettel_post_APIContext))]
    partial class Viettel_post_APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Viettel_post_API.Models.ChuyenXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DanhSachXeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<int>("LanThu")
                        .HasColumnType("int");

                    b.Property<string>("MaChuyenApi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianSync")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhSachXeId");

                    b.HasIndex("MaChuyenApi")
                        .IsUnique();

                    b.ToTable("ChuyenXes");
                });

            modelBuilder.Entity("Viettel_post_API.Models.DanhSachXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLaiXe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhSachXes");
                });

            modelBuilder.Entity("Viettel_post_API.Models.HangHoaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChuyenXeId")
                        .HasColumnType("int");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenXeId");

                    b.ToTable("HangHoaItems");
                });

            modelBuilder.Entity("Viettel_post_API.Models.ChuyenXe", b =>
                {
                    b.HasOne("Viettel_post_API.Models.DanhSachXe", "DanhSachXe")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("DanhSachXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhSachXe");
                });

            modelBuilder.Entity("Viettel_post_API.Models.HangHoaItem", b =>
                {
                    b.HasOne("Viettel_post_API.Models.ChuyenXe", "ChuyenXe")
                        .WithMany("HangHoas")
                        .HasForeignKey("ChuyenXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenXe");
                });

            modelBuilder.Entity("Viettel_post_API.Models.ChuyenXe", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("Viettel_post_API.Models.DanhSachXe", b =>
                {
                    b.Navigation("ChuyenXes");
                });
#pragma warning restore 612, 618
        }
    }
}
