// <auto-generated />
using System;
using LedApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LedApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230728071746_ThayDoi28_7")]
    partial class ThayDoi28_7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LedApp.Models.ChitietNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NhapId")
                        .HasColumnType("int");

                    b.Property<long>("Soluong")
                        .HasColumnType("bigint");

                    b.Property<string>("donvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhapId");

                    b.ToTable("ChitietNhap");
                });

            modelBuilder.Entity("LedApp.Models.ChitietXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("SoluongCH")
                        .HasColumnType("bigint");

                    b.Property<long>("SoluongD")
                        .HasColumnType("bigint");

                    b.Property<string>("donviCH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donviD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dulieuxuatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dulieuxuatId");

                    b.ToTable("ChitietXuat");
                });

            modelBuilder.Entity("LedApp.Models.CuaNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CuaNhap");
                });

            modelBuilder.Entity("LedApp.Models.CuaXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CuaXuat");
                });

            modelBuilder.Entity("LedApp.Models.dulieuxuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CongRa")
                        .HasColumnType("int");

                    b.Property<int>("CuaXuatId")
                        .HasColumnType("int");

                    b.Property<int?>("GioXuat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhutXuat")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CuaXuatId");

                    b.ToTable("dulieuxuat");
                });

            modelBuilder.Entity("LedApp.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("Tels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nguoiDungs");
                });

            modelBuilder.Entity("LedApp.Models.Nhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CongVao")
                        .HasColumnType("int");

                    b.Property<int>("CuaNhapId")
                        .HasColumnType("int");

                    b.Property<int?>("GioNhap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhutNhap")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CuaNhapId");

                    b.ToTable("Nhap");
                });

            modelBuilder.Entity("LedApp.Models.ChitietNhap", b =>
                {
                    b.HasOne("LedApp.Models.Nhap", "Nhap")
                        .WithMany("ChitietNhaps")
                        .HasForeignKey("NhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhap");
                });

            modelBuilder.Entity("LedApp.Models.ChitietXuat", b =>
                {
                    b.HasOne("LedApp.Models.dulieuxuat", "dulieuxuat")
                        .WithMany("ChitietXuat")
                        .HasForeignKey("dulieuxuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dulieuxuat");
                });

            modelBuilder.Entity("LedApp.Models.dulieuxuat", b =>
                {
                    b.HasOne("LedApp.Models.CuaXuat", "CuaXuat")
                        .WithMany("dulieuxuat")
                        .HasForeignKey("CuaXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaXuat");
                });

            modelBuilder.Entity("LedApp.Models.Nhap", b =>
                {
                    b.HasOne("LedApp.Models.CuaNhap", "CuaNhap")
                        .WithMany("Nhaps")
                        .HasForeignKey("CuaNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaNhap");
                });

            modelBuilder.Entity("LedApp.Models.CuaNhap", b =>
                {
                    b.Navigation("Nhaps");
                });

            modelBuilder.Entity("LedApp.Models.CuaXuat", b =>
                {
                    b.Navigation("dulieuxuat");
                });

            modelBuilder.Entity("LedApp.Models.dulieuxuat", b =>
                {
                    b.Navigation("ChitietXuat");
                });

            modelBuilder.Entity("LedApp.Models.Nhap", b =>
                {
                    b.Navigation("ChitietNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
